INSERT INTO country VALUES (DEFAULT, 'Afghanistan');
INSERT INTO country VALUES (DEFAULT, 'Albania');
INSERT INTO country VALUES (DEFAULT, 'Algeria');
INSERT INTO country VALUES (DEFAULT, 'American Samoa');
INSERT INTO country VALUES (DEFAULT, 'Andorra');
INSERT INTO country VALUES (DEFAULT, 'Angola');
INSERT INTO country VALUES (DEFAULT, 'Anguilla');
INSERT INTO country VALUES (DEFAULT, 'Antarctica');
INSERT INTO country VALUES (DEFAULT, 'Antigua and Barbuda');
INSERT INTO country VALUES (DEFAULT, 'Argentina');
INSERT INTO country VALUES (DEFAULT, 'Armenia');
INSERT INTO country VALUES (DEFAULT, 'Aruba');
INSERT INTO country VALUES (DEFAULT, 'Australia');
INSERT INTO country VALUES (DEFAULT, 'Austria');
INSERT INTO country VALUES (DEFAULT, 'Azerbaijan');
INSERT INTO country VALUES (DEFAULT, 'Bahamas');
INSERT INTO country VALUES (DEFAULT, 'Bahrain');
INSERT INTO country VALUES (DEFAULT, 'Bangladesh');
INSERT INTO country VALUES (DEFAULT, 'Barbados');
INSERT INTO country VALUES (DEFAULT, 'Belarus');
INSERT INTO country VALUES (DEFAULT, 'Belgium');
INSERT INTO country VALUES (DEFAULT, 'Belize');
INSERT INTO country VALUES (DEFAULT, 'Benin');
INSERT INTO country VALUES (DEFAULT, 'Bermuda');
INSERT INTO country VALUES (DEFAULT, 'Bhutan');
INSERT INTO country VALUES (DEFAULT, 'Bolivia');
INSERT INTO country VALUES (DEFAULT, 'Bosnia and Herzegovina');
INSERT INTO country VALUES (DEFAULT, 'Botswana');
INSERT INTO country VALUES (DEFAULT, 'Bouvet Island');
INSERT INTO country VALUES (DEFAULT, 'Brazil');
INSERT INTO country VALUES (DEFAULT, 'British Indian Ocean Territory');
INSERT INTO country VALUES (DEFAULT, 'Brunei Darussalam');
INSERT INTO country VALUES (DEFAULT, 'Bulgaria');
INSERT INTO country VALUES (DEFAULT, 'Burkina Faso');
INSERT INTO country VALUES (DEFAULT, 'Burundi');
INSERT INTO country VALUES (DEFAULT, 'Cambodia');
INSERT INTO country VALUES (DEFAULT, 'Cameroon');
INSERT INTO country VALUES (DEFAULT, 'Canada');
INSERT INTO country VALUES (DEFAULT, 'Cape Verde');
INSERT INTO country VALUES (DEFAULT, 'Cayman Islands');
INSERT INTO country VALUES (DEFAULT, 'Central African Republic');
INSERT INTO country VALUES (DEFAULT, 'Chad');
INSERT INTO country VALUES (DEFAULT, 'Chile');
INSERT INTO country VALUES (DEFAULT, 'China');
INSERT INTO country VALUES (DEFAULT, 'Christmas Island');
INSERT INTO country VALUES (DEFAULT, 'Cocos (Keeling) Islands');
INSERT INTO country VALUES (DEFAULT, 'Colombia');
INSERT INTO country VALUES (DEFAULT, 'Comoros');
INSERT INTO country VALUES (DEFAULT, 'Congo');
INSERT INTO country VALUES (DEFAULT, 'Cook Islands');
INSERT INTO country VALUES (DEFAULT, 'Costa Rica');
INSERT INTO country VALUES (DEFAULT, 'Croatia (Hrvatska)');
INSERT INTO country VALUES (DEFAULT, 'Cuba');
INSERT INTO country VALUES (DEFAULT, 'Cyprus');
INSERT INTO country VALUES (DEFAULT, 'Czech Republic');
INSERT INTO country VALUES (DEFAULT, 'Denmark');
INSERT INTO country VALUES (DEFAULT, 'Djibouti');
INSERT INTO country VALUES (DEFAULT, 'Dominica');
INSERT INTO country VALUES (DEFAULT, 'Dominican Republic');
INSERT INTO country VALUES (DEFAULT, 'East Timor');
INSERT INTO country VALUES (DEFAULT, 'Ecuador');
INSERT INTO country VALUES (DEFAULT, 'Egypt');
INSERT INTO country VALUES (DEFAULT, 'El Salvador');
INSERT INTO country VALUES (DEFAULT, 'Equatorial Guinea');
INSERT INTO country VALUES (DEFAULT, 'Eritrea');
INSERT INTO country VALUES (DEFAULT, 'Estonia');
INSERT INTO country VALUES (DEFAULT, 'Ethiopia');
INSERT INTO country VALUES (DEFAULT, 'Falkland Islands (Malvinas)');
INSERT INTO country VALUES (DEFAULT, 'Faroe Islands');
INSERT INTO country VALUES (DEFAULT, 'Fiji');
INSERT INTO country VALUES (DEFAULT, 'Finland');
INSERT INTO country VALUES (DEFAULT, 'France');
INSERT INTO country VALUES (DEFAULT, 'France, Metropolitan');
INSERT INTO country VALUES (DEFAULT, 'French Guiana');
INSERT INTO country VALUES (DEFAULT, 'French Polynesia');
INSERT INTO country VALUES (DEFAULT, 'French Southern Territories');
INSERT INTO country VALUES (DEFAULT, 'Gabon');
INSERT INTO country VALUES (DEFAULT, 'Gambia');
INSERT INTO country VALUES (DEFAULT, 'Georgia');
INSERT INTO country VALUES (DEFAULT, 'Germany');
INSERT INTO country VALUES (DEFAULT, 'Ghana');
INSERT INTO country VALUES (DEFAULT, 'Gibraltar');
INSERT INTO country VALUES (DEFAULT, 'Guernsey');
INSERT INTO country VALUES (DEFAULT, 'Greece');
INSERT INTO country VALUES (DEFAULT, 'Greenland');
INSERT INTO country VALUES (DEFAULT, 'Grenada');
INSERT INTO country VALUES (DEFAULT, 'Guadeloupe');
INSERT INTO country VALUES (DEFAULT, 'Guam');
INSERT INTO country VALUES (DEFAULT, 'Guatemala');
INSERT INTO country VALUES (DEFAULT, 'Guinea');
INSERT INTO country VALUES (DEFAULT, 'Guinea-Bissau');
INSERT INTO country VALUES (DEFAULT, 'Guyana');
INSERT INTO country VALUES (DEFAULT, 'Haiti');
INSERT INTO country VALUES (DEFAULT, 'Heard and Mc Donald Islands');
INSERT INTO country VALUES (DEFAULT, 'Honduras');
INSERT INTO country VALUES (DEFAULT, 'Hong Kong');
INSERT INTO country VALUES (DEFAULT, 'Hungary');
INSERT INTO country VALUES (DEFAULT, 'Iceland');
INSERT INTO country VALUES (DEFAULT, 'India');
INSERT INTO country VALUES (DEFAULT, 'Isle of Man');
INSERT INTO country VALUES (DEFAULT, 'Indonesia');
INSERT INTO country VALUES (DEFAULT, 'Iran (Islamic Republic of)');
INSERT INTO country VALUES (DEFAULT, 'Iraq');
INSERT INTO country VALUES (DEFAULT, 'Ireland');
INSERT INTO country VALUES (DEFAULT, 'Israel');
INSERT INTO country VALUES (DEFAULT, 'Italy');
INSERT INTO country VALUES (DEFAULT, 'Ivory Coast');
INSERT INTO country VALUES (DEFAULT, 'Jersey');
INSERT INTO country VALUES (DEFAULT, 'Jamaica');
INSERT INTO country VALUES (DEFAULT, 'Japan');
INSERT INTO country VALUES (DEFAULT, 'Jordan');
INSERT INTO country VALUES (DEFAULT, 'Kazakhstan');
INSERT INTO country VALUES (DEFAULT, 'Kenya');
INSERT INTO country VALUES (DEFAULT, 'Kiribati');
INSERT INTO country VALUES (DEFAULT, 'Korea, Democratic People''s Republic of');
INSERT INTO country VALUES (DEFAULT, 'Korea, Republic of');
INSERT INTO country VALUES (DEFAULT, 'Kosovo');
INSERT INTO country VALUES (DEFAULT, 'Kuwait');
INSERT INTO country VALUES (DEFAULT, 'Kyrgyzstan');
INSERT INTO country VALUES (DEFAULT, 'Lao People''s Democratic Republic');
INSERT INTO country VALUES (DEFAULT, 'Latvia');
INSERT INTO country VALUES (DEFAULT, 'Lebanon');
INSERT INTO country VALUES (DEFAULT, 'Lesotho');
INSERT INTO country VALUES (DEFAULT, 'Liberia');
INSERT INTO country VALUES (DEFAULT, 'Libyan Arab Jamahiriya');
INSERT INTO country VALUES (DEFAULT, 'Liechtenstein');
INSERT INTO country VALUES (DEFAULT, 'Lithuania');
INSERT INTO country VALUES (DEFAULT, 'Luxembourg');
INSERT INTO country VALUES (DEFAULT, 'Macau');
INSERT INTO country VALUES (DEFAULT, 'Macedonia');
INSERT INTO country VALUES (DEFAULT, 'Madagascar');
INSERT INTO country VALUES (DEFAULT, 'Malawi');
INSERT INTO country VALUES (DEFAULT, 'Malaysia');
INSERT INTO country VALUES (DEFAULT, 'Maldives');
INSERT INTO country VALUES (DEFAULT, 'Mali');
INSERT INTO country VALUES (DEFAULT, 'Malta');
INSERT INTO country VALUES (DEFAULT, 'Marshall Islands');
INSERT INTO country VALUES (DEFAULT, 'Martinique');
INSERT INTO country VALUES (DEFAULT, 'Mauritania');
INSERT INTO country VALUES (DEFAULT, 'Mauritius');
INSERT INTO country VALUES (DEFAULT, 'Mayotte');
INSERT INTO country VALUES (DEFAULT, 'Mexico');
INSERT INTO country VALUES (DEFAULT, 'Micronesia, Federated States of');
INSERT INTO country VALUES (DEFAULT, 'Moldova, Republic of');
INSERT INTO country VALUES (DEFAULT, 'Monaco');
INSERT INTO country VALUES (DEFAULT, 'Mongolia');
INSERT INTO country VALUES (DEFAULT, 'Montenegro');
INSERT INTO country VALUES (DEFAULT, 'Montserrat');
INSERT INTO country VALUES (DEFAULT, 'Morocco');
INSERT INTO country VALUES (DEFAULT, 'Mozambique');
INSERT INTO country VALUES (DEFAULT, 'Myanmar');
INSERT INTO country VALUES (DEFAULT, 'Namibia');
INSERT INTO country VALUES (DEFAULT, 'Nauru');
INSERT INTO country VALUES (DEFAULT, 'Nepal');
INSERT INTO country VALUES (DEFAULT, 'Netherlands');
INSERT INTO country VALUES (DEFAULT, 'Netherlands Antilles');
INSERT INTO country VALUES (DEFAULT, 'New Caledonia');
INSERT INTO country VALUES (DEFAULT, 'New Zealand');
INSERT INTO country VALUES (DEFAULT, 'Nicaragua');
INSERT INTO country VALUES (DEFAULT, 'Niger');
INSERT INTO country VALUES (DEFAULT, 'Nigeria');
INSERT INTO country VALUES (DEFAULT, 'Niue');
INSERT INTO country VALUES (DEFAULT, 'Norfolk Island');
INSERT INTO country VALUES (DEFAULT, 'Northern Mariana Islands');
INSERT INTO country VALUES (DEFAULT, 'Norway');
INSERT INTO country VALUES (DEFAULT, 'Oman');
INSERT INTO country VALUES (DEFAULT, 'Pakistan');
INSERT INTO country VALUES (DEFAULT, 'Palau');
INSERT INTO country VALUES (DEFAULT, 'Palestine');
INSERT INTO country VALUES (DEFAULT, 'Panama');
INSERT INTO country VALUES (DEFAULT, 'Papua New Guinea');
INSERT INTO country VALUES (DEFAULT, 'Paraguay');
INSERT INTO country VALUES (DEFAULT, 'Peru');
INSERT INTO country VALUES (DEFAULT, 'Philippines');
INSERT INTO country VALUES (DEFAULT, 'Pitcairn');
INSERT INTO country VALUES (DEFAULT, 'Poland');
INSERT INTO country VALUES (DEFAULT, 'Portugal');
INSERT INTO country VALUES (DEFAULT, 'Puerto Rico');
INSERT INTO country VALUES (DEFAULT, 'Qatar');
INSERT INTO country VALUES (DEFAULT, 'Reunion');
INSERT INTO country VALUES (DEFAULT, 'Romania');
INSERT INTO country VALUES (DEFAULT, 'Russian Federation');
INSERT INTO country VALUES (DEFAULT, 'Rwanda');
INSERT INTO country VALUES (DEFAULT, 'Saint Kitts and Nevis');
INSERT INTO country VALUES (DEFAULT, 'Saint Lucia');
INSERT INTO country VALUES (DEFAULT, 'Saint Vincent and the Grenadines');
INSERT INTO country VALUES (DEFAULT, 'Samoa');
INSERT INTO country VALUES (DEFAULT, 'San Marino');
INSERT INTO country VALUES (DEFAULT, 'Sao Tome and Principe');
INSERT INTO country VALUES (DEFAULT, 'Saudi Arabia');
INSERT INTO country VALUES (DEFAULT, 'Senegal');
INSERT INTO country VALUES (DEFAULT, 'Serbia');
INSERT INTO country VALUES (DEFAULT, 'Seychelles');
INSERT INTO country VALUES (DEFAULT, 'Sierra Leone');
INSERT INTO country VALUES (DEFAULT, 'Singapore');
INSERT INTO country VALUES (DEFAULT, 'Slovakia');
INSERT INTO country VALUES (DEFAULT, 'Slovenia');
INSERT INTO country VALUES (DEFAULT, 'Solomon Islands');
INSERT INTO country VALUES (DEFAULT, 'Somalia');
INSERT INTO country VALUES (DEFAULT, 'South Africa');
INSERT INTO country VALUES (DEFAULT, 'South Georgia South Sandwich Islands');
INSERT INTO country VALUES (DEFAULT, 'Spain');
INSERT INTO country VALUES (DEFAULT, 'Sri Lanka');
INSERT INTO country VALUES (DEFAULT, 'St. Helena');
INSERT INTO country VALUES (DEFAULT, 'St. Pierre and Miquelon');
INSERT INTO country VALUES (DEFAULT, 'Sudan');
INSERT INTO country VALUES (DEFAULT, 'Suriname');
INSERT INTO country VALUES (DEFAULT, 'Svalbard and Jan Mayen Islands');
INSERT INTO country VALUES (DEFAULT, 'Swaziland');
INSERT INTO country VALUES (DEFAULT, 'Sweden');
INSERT INTO country VALUES (DEFAULT, 'Switzerland');
INSERT INTO country VALUES (DEFAULT, 'Syrian Arab Republic');
INSERT INTO country VALUES (DEFAULT, 'Taiwan');
INSERT INTO country VALUES (DEFAULT, 'Tajikistan');
INSERT INTO country VALUES (DEFAULT, 'Tanzania, United Republic of');
INSERT INTO country VALUES (DEFAULT, 'Thailand');
INSERT INTO country VALUES (DEFAULT, 'Togo');
INSERT INTO country VALUES (DEFAULT, 'Tokelau');
INSERT INTO country VALUES (DEFAULT, 'Tonga');
INSERT INTO country VALUES (DEFAULT, 'Trinidad and Tobago');
INSERT INTO country VALUES (DEFAULT, 'Tunisia');
INSERT INTO country VALUES (DEFAULT, 'Turkey');
INSERT INTO country VALUES (DEFAULT, 'Turkmenistan');
INSERT INTO country VALUES (DEFAULT, 'Turks and Caicos Islands');
INSERT INTO country VALUES (DEFAULT, 'Tuvalu');
INSERT INTO country VALUES (DEFAULT, 'Uganda');
INSERT INTO country VALUES (DEFAULT, 'Ukraine');
INSERT INTO country VALUES (DEFAULT, 'United Arab Emirates');
INSERT INTO country VALUES (DEFAULT, 'United Kingdom');
INSERT INTO country VALUES (DEFAULT, 'United States');
INSERT INTO country VALUES (DEFAULT, 'United States minor outlying islands');
INSERT INTO country VALUES (DEFAULT, 'Uruguay');
INSERT INTO country VALUES (DEFAULT, 'Uzbekistan');
INSERT INTO country VALUES (DEFAULT, 'Vanuatu');
INSERT INTO country VALUES (DEFAULT, 'Vatican City State');
INSERT INTO country VALUES (DEFAULT, 'Venezuela');
INSERT INTO country VALUES (DEFAULT, 'Vietnam');
INSERT INTO country VALUES (DEFAULT, 'Virgin Islands (British)');
INSERT INTO country VALUES (DEFAULT, 'Virgin Islands (U.S.)');
INSERT INTO country VALUES (DEFAULT, 'Wallis and Futuna Islands');
INSERT INTO country VALUES (DEFAULT, 'Western Sahara');
INSERT INTO country VALUES (DEFAULT, 'Yemen');
INSERT INTO country VALUES (DEFAULT, 'Zaire');
INSERT INTO country VALUES (DEFAULT, 'Zambia');
INSERT INTO country VALUES (DEFAULT, 'Zimbabwe');